### PR TITLE
cleanup contracts

### PR DESCRIPTION
**Pull request by msilucifer**
Cleanup Contracts for this issue (https://github.com/plexus-money/contracts/issues/22)

### CODE REVIEW

**Review by terminator0x — CHANGES_REQUESTED** [review]
Please fix the failing tests before I review

**Review by terminator0x — CHANGES_REQUESTED** [review]
@msilucifer This looks great so far, just 3 things.

1. I'm still seeing alot of hardcoded token addresses in a lot of the contracts, this should not be the case. Please create a .env file that contains these token addresses and during deployment pass these addresses as parameters in the constructor to initialize the various addresses. 
 

-  Basically no token address should be hardcoded in the contracts at all, instead the .e.v file should contain the token addresses for the different environments i.e. mainnet, rinkeby e.t.c

- So just to quote the issue again, "Create a custom hardhat script for deployment that'll read the address values for the various hardcoded tokens & contracts from a .env file and pass them to the respective constructors during deployment, so that they are set during deployment."

2. I'm not seeing a deployment script which I could call via the cli in node.js to deploy all the contracts at once. Please read the [hardhat deployment](https://hardhat.org/guides/deploying.html) guide to see what I mean.

-  If necessary for this, rename the current scripts folder to "AuditScripts" and then create a new "scripts" folder which will now contain the "deploy.js" that I can call and pass a particular network parameter and then it automatically deploys the contracts to that network.

3. Finally I see you deleted the tier1Staking.sol, tier2Aave.sol, oracle.sol and many other files, why did you do this? we need those contracts

**Comment by msilucifer** [comment]
Thanks for your review.
1. I will try as you want.
2. I uploaded only cleanup contract code without the deployment code. I am writing this one now.
3. I didn't delete these files , I just renamed them. (i.e. `tier1Staking.sol` -> `Tier1FarmController.sol`, `oracle.sol` -> `PlexusOracle.sol`

**Comment by terminator0x** [comment]
> Thanks for your review.
> 
> 1. I will try as you want.
> 2. I uploaded only cleanup contract code without the deployment code. I am writing this one now.
> 3. I didn't delete these files , I just renamed them. (i.e. `tier1Staking.sol` -> `Tier1FarmController.sol`, `oracle.sol` -> `PlexusOracle.sol`)

Ok thanks for the reply, please update me when the PR has been updated with these changes. 

Also undo the rename so as not cause a conflict with another pending conflict, we'll do the renaming in another issue :slightly_smiling_face:

**Comment by terminator0x** [comment]
@msilucifer please rebase against master and solve the conflicts, thanks.

**Pull request merged**
